[project]
name = "tizim-dasturlash-amaliyot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "environs>=14.5.0",
    "fastapi[all]>=0.123.9",
    "psutil>=7.1.3",
    "uvicorn>=0.38.0",
]
